# Generated by Django 4.1.7 on 2023-03-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('adult_phone_number', models.CharField(default=0, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('attendance_status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='attendance.child')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adult', to='attendance.adult')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child', to='attendance.child')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='attendance.staff')),
            ],
        ),
        migrations.AddField(
            model_name='adult',
            name='children',
            field=models.ManyToManyField(related_name='adults', to='attendance.child'),
        ),
    ]
